import type { Category, Tool, Tag } from '@/types/tool'

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'AI 写作',
    slug: 'ai-writing',
    sort_order: 1,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'AI 绘画',
    slug: 'ai-art',
    sort_order: 2,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 3,
    name: 'AI 编程',
    slug: 'ai-coding',
    sort_order: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'AI 视频',
    slug: 'ai-video',
    sort_order: 4,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'AI 语音',
    slug: 'ai-audio',
    sort_order: 5,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'AI 翻译',
    slug: 'ai-translation',
    sort_order: 6,
    created_at: '2024-01-01T00:00:00Z',
  },
]

export const mockTags: Tag[] = [
  { id: 1, name: '免费' },
  { id: 2, name: '中文' },
  { id: 3, name: '开源' },
  { id: 4, name: 'GPT-4' },
  { id: 5, name: 'Midjourney' },
  { id: 6, name: 'Stable Diffusion' },
]

export const mockTools: Tool[] = [
  {
    id: 1,
    name: 'ChatGPT',
    slug: 'chatgpt',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/brands/openai.svg',
    short_description: 'OpenAI 开发的大型语言模型',
    description: 'ChatGPT 是 OpenAI 开发的先进对话式 AI 模型，具备强大的文本理解、生成和多任务处理能力。支持对话、写作、编程、翻译等多种场景。',
    website_url: 'https://chat.openai.com',
    category_id: 1,
    is_free: false,
    is_zh: false,
    status: 'published',
    recommended: true,
    created_at: '2024-01-01T00:00:00Z',
    category: mockCategories[0],
    tags: [mockTags[3]],
  },
  {
    id: 2,
    name: 'Claude',
    slug: 'claude',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/robot.svg',
    short_description: 'Anthropic 开发的 AI 助手',
    description: 'Claude 是 Anthropic 公司开发的高性能 AI 助手，以其出色的对话能力和安全性而闻名。支持长文本处理、代码编写、文档分析等任务。',
    website_url: 'https://claude.ai',
    category_id: 1,
    is_free: true,
    is_zh: true,
    status: 'published',
    recommended: true,
    created_at: '2024-01-02T00:00:00Z',
    category: mockCategories[0],
    tags: [mockTags[0], mockTags[1]],
  },
  {
    id: 3,
    name: 'Midjourney',
    slug: 'midjourney',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/palette.svg',
    short_description: '强大的 AI 绘画生成工具',
    description: 'Midjourney 是目前最流行的 AI 图像生成工具之一，通过简单的文本提示即可生成高质量的艺术作品、插画、照片等图像。',
    website_url: 'https://midjourney.com',
    category_id: 2,
    is_free: false,
    is_zh: false,
    status: 'published',
    recommended: true,
    created_at: '2024-01-03T00:00:00Z',
    category: mockCategories[1],
    tags: [mockTags[4]],
  },
  {
    id: 4,
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/wand-magic-sparkles.svg',
    short_description: '开源的 AI 图像生成模型',
    description: 'Stable Diffusion 是一个开源的 AI 图像生成模型，用户可以在本地部署，完全控制生成过程，支持各种风格和用途的图像创作。',
    website_url: 'https://stability.ai',
    category_id: 2,
    is_free: true,
    is_zh: true,
    status: 'published',
    recommended: true,
    created_at: '2024-01-04T00:00:00Z',
    category: mockCategories[1],
    tags: [mockTags[2], mockTags[5]],
  },
  {
    id: 5,
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/brands/github.svg',
    short_description: 'GitHub AI 编程助手',
    description: 'GitHub Copilot 是基于 OpenAI Codex 开发的 AI 编程助手，能够根据代码上下文智能生成代码片段、函数、注释，大幅提升开发效率。',
    website_url: 'https://github.com/features/copilot',
    category_id: 3,
    is_free: false,
    is_zh: false,
    status: 'published',
    recommended: true,
    created_at: '2024-01-05T00:00:00Z',
    category: mockCategories[2],
    tags: [],
  },
  {
    id: 6,
    name: 'Cursor',
    slug: 'cursor',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/code.svg',
    short_description: 'AI 驱动的代码编辑器',
    description: 'Cursor 是一款专为 AI 编程设计的代码编辑器，集成了强大的 AI 功能，可以理解整个代码库，提供智能补全、重构、问答等服务。',
    website_url: 'https://cursor.sh',
    category_id: 3,
    is_free: true,
    is_zh: true,
    status: 'published',
    recommended: true,
    created_at: '2024-01-06T00:00:00Z',
    category: mockCategories[2],
    tags: [mockTags[0], mockTags[1]],
  },
  {
    id: 7,
    name: 'Runway',
    slug: 'runway',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/film.svg',
    short_description: '专业 AI 视频创作平台',
    description: 'Runway 是一个专业的 AI 视频创作平台，提供文本生成视频、视频编辑、绿幕、风格迁移等多种功能，适合影视制作、广告创意等行业。',
    website_url: 'https://runway.ml',
    category_id: 4,
    is_free: false,
    is_zh: false,
    status: 'published',
    recommended: false,
    created_at: '2024-01-07T00:00:00Z',
    category: mockCategories[3],
    tags: [],
  },
  {
    id: 8,
    name: 'HeyGen',
    slug: 'heygen',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/user-tie.svg',
    short_description: 'AI 数字人视频生成',
    description: 'HeyGen 是一个强大的 AI 数字人视频生成平台，只需输入文本即可生成高质量的数字人视频，支持多语言、多角色，适合企业宣传、教育培训等场景。',
    website_url: 'https://heygen.com',
    category_id: 4,
    is_free: true,
    is_zh: true,
    status: 'published',
    recommended: false,
    created_at: '2024-01-08T00:00:00Z',
    category: mockCategories[3],
    tags: [mockTags[0], mockTags[1]],
  },
  {
    id: 9,
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/microphone-lines.svg',
    short_description: '顶级 AI 语音合成',
    description: 'ElevenLabs 提供业界领先的 AI 语音合成服务，能够生成极其自然的语音效果，支持多种语言和音色，适合有声书、配音、播客等应用。',
    website_url: 'https://elevenlabs.io',
    category_id: 5,
    is_free: false,
    is_zh: true,
    status: 'published',
    recommended: false,
    created_at: '2024-01-09T00:00:00Z',
    category: mockCategories[4],
    tags: [mockTags[1]],
  },
  {
    id: 10,
    name: 'DeepL',
    slug: 'deepl',
    logo_url: 'https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.4.0/svgs/solid/language.svg',
    short_description: '高精度 AI 翻译工具',
    description: 'DeepL 是一款基于 AI 的翻译工具，以其出色的翻译精度和自然语言处理能力而闻名，支持多种语言互译，翻译质量远超传统工具。',
    website_url: 'https://deepl.com',
    category_id: 6,
    is_free: true,
    is_zh: true,
    status: 'published',
    recommended: true,
    created_at: '2024-01-10T00:00:00Z',
    category: mockCategories[5],
    tags: [mockTags[0], mockTags[1]],
  },
]

export const getMockToolBySlug = (slug: string): Tool | undefined => {
  return mockTools.find((tool) => tool.slug === slug)
}

export const getMockToolsByCategory = (categoryId: number): Tool[] => {
  return mockTools.filter((tool) => tool.category_id === categoryId)
}

export const searchMockTools = (keyword: string): Tool[] => {
  const lowerKeyword = keyword.toLowerCase()
  return mockTools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerKeyword) ||
      tool.short_description.toLowerCase().includes(lowerKeyword) ||
      tool.description.toLowerCase().includes(lowerKeyword)
  )
}
